/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthOtpCaptchaBlock: typeof import('./components/auth/AuthOtpCaptchaBlock.vue')['default']
    AuthPasswordField: typeof import('./components/auth/AuthPasswordField.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    PageSectionHeading: typeof import('./components/PageSectionHeading.vue')['default']
    PlanHeatmapGrid: typeof import('./components/PlanHeatmapGrid.vue')['default']
    PlanPomodoroBar: typeof import('./components/PlanPomodoroBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiCheckinSubmissionDrawer: typeof import('./components/UiCheckinSubmissionDrawer.vue')['default']
    UiConfirmDialog: typeof import('./components/UiConfirmDialog.vue')['default']
    UiEllipsisTooltip: typeof import('./components/UiEllipsisTooltip.vue')['default']
    UiErrorToast: typeof import('./components/UiErrorToast.vue')['default']
    UiModalShell: typeof import('./components/UiModalShell.vue')['default']
    UiMoreDropdown: typeof import('./components/UiMoreDropdown.vue')['default']
    UiSunriseSelect: typeof import('./components/UiSunriseSelect.vue')['default']
    UiSwitchToggle: typeof import('./components/UiSwitchToggle.vue')['default']
    UserAvatarBadge: typeof import('./components/UserAvatarBadge.vue')['default']
  }
}
